# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DisplayMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DisplayMovie
  pod "AlamofireImage"
  pod "Alamofire"

  target 'DisplayMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DisplayMovieUITests' do
    # Pods for testing
  end

end
